# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notifyer_pb2 as notifyer__pb2


class NorifyerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNotify = channel.unary_unary(
            '/Norifyer/SendNotify',
            request_serializer=notifyer__pb2.MsgRequest.SerializeToString,
            response_deserializer=notifyer__pb2.MsgReply.FromString,
        )


class NorifyerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendNotify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NorifyerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SendNotify': grpc.unary_unary_rpc_method_handler(
            servicer.SendNotify,
            request_deserializer=notifyer__pb2.MsgRequest.FromString,
            response_serializer=notifyer__pb2.MsgReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Norifyer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class Norifyer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendNotify(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Norifyer/SendNotify',
                                             notifyer__pb2.MsgRequest.SerializeToString,
                                             notifyer__pb2.MsgReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
